CI: implement release pipeline for GitHub and PyPI (#3743)
A maintainer can now run the Packaging workflow manually, which
builds the release assets and prepares a release for deployment.
The maintainer can then review and approve the release.

This replaces the old manual process of creating GitHub releases.

diff --git a/.github/workflows/packaging.yml b/.github/workflows/packaging.yml
--- a/.github/workflows/packaging.yml
+++ b/.github/workflows/packaging.yml
@@ -2,10 +2,42 @@
 # SPDX-License-Identifier: GPL-3.0-or-later
 
 name: Packaging
-on: [push, pull_request]
+on:
+  push:
+  pull_request:
+  workflow_dispatch:
+    inputs:
+      create_release:
+        description: Create new release
+        type: boolean
+        required: false
+
 permissions: {}
 
 jobs:
+
+  python-dist:
+    runs-on: ubuntu-latest
+    timeout-minutes: 15
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v6
+        with:
+          persist-credentials: false
+
+      - name: Install dependencies
+        run: |
+          sudo apt update
+          sudo apt install gettext python3-build
+
+      - name: Build package
+        run: python -m build
+
+      - name: Upload artifacts
+        uses: actions/upload-artifact@v7
+        with:
+          name: python-dist
+          path: dist/
 
   debian:
     runs-on: ubuntu-latest
@@ -278,3 +310,205 @@ jobs:
         with:
           name: macos-${{ matrix.arch }}-installer
           path: build-aux/macos/build/*.dmg
+
+  checksums:
+    needs: [python-dist, debian, flatpak, snap, appimage, windows, macos]
+    runs-on: ubuntu-slim
+    timeout-minutes: 15
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v6
+        with:
+          persist-credentials: false
+
+      - name: Download artifacts
+        uses: actions/download-artifact@v8
+        with:
+          path: dist/
+          skip-decompress: true
+          merge-multiple: true
+
+      - name: Generate checksums
+        run: python data/scripts/generate_sha256_checksums.py
+
+      - name: Verify checksums
+        run: cd dist && sha256sum --check ./*.sha256
+
+      - name: Verify list of artifacts
+        run: |
+          cd dist
+          ls \
+            appimage-x86_64-package.zip \
+            appimage-x86_64-package.zip.sha256 \
+            debian-package.zip \
+            debian-package.zip.sha256 \
+            flatpak-aarch64-package.zip \
+            flatpak-aarch64-package.zip.sha256 \
+            flatpak-x86_64-package.zip \
+            flatpak-x86_64-package.zip.sha256 \
+            macos-arm64-installer.zip \
+            macos-arm64-installer.zip.sha256 \
+            macos-x86_64-installer.zip \
+            macos-x86_64-installer.zip.sha256 \
+            python-dist.zip \
+            python-dist.zip.sha256 \
+            snap-arm64-package.zip \
+            snap-arm64-package.zip.sha256 \
+            snap-x86_64-package.zip \
+            snap-x86_64-package.zip.sha256 \
+            windows-arm64-installer.zip \
+            windows-arm64-installer.zip.sha256 \
+            windows-arm64-portable.zip \
+            windows-arm64-portable.zip.sha256 \
+            windows-x86_64-installer.zip \
+            windows-x86_64-installer.zip.sha256 \
+            windows-x86_64-portable.zip \
+            windows-x86_64-portable.zip.sha256
+
+      - name: Archive installer artifacts
+        uses: actions/upload-artifact@v7
+        with:
+          name: checksums
+          path: dist/*.sha256
+
+  attestation:
+    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
+    needs: checksums
+    runs-on: ubuntu-slim
+    timeout-minutes: 15
+    permissions:
+      id-token: write
+      attestations: write
+      artifact-metadata: write
+    steps:
+      - name: Download artifacts
+        uses: actions/download-artifact@v8
+        with:
+          path: dist/
+          skip-decompress: true
+          merge-multiple: true
+
+      - name: Extract checksums
+        run: cd dist && unzip checksums.zip
+
+      - name: Attest
+        uses: actions/attest@v4
+        with:
+          subject-path: dist/
+
+  metadata:
+    needs: checksums
+    runs-on: ubuntu-slim
+    timeout-minutes: 15
+    outputs:
+      version: ${{ steps.version.outputs.version }}
+      notes: ${{ steps.notes.outputs.notes }}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v6
+        with:
+          persist-credentials: false
+
+      - name: Store version
+        id: version
+        run: |
+          VERSION="$(python -m pynicotine --ci-version)"
+          echo "::notice::Version: $VERSION"
+          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
+
+      - name: Store notes
+        id: notes
+        env:
+          VERSION: ${{ steps.version.outputs.version }}
+        run: |
+          NOTES="$(python data/scripts/extract_release_notes.py "$VERSION")"
+          echo "Release notes: $NOTES"
+          {
+            echo "notes<<EOF"
+            echo "$NOTES"
+            echo "EOF"
+          } >> "$GITHUB_OUTPUT"
+
+      - name: Validate version
+        if: inputs.create_release
+        env:
+          VERSION: ${{ steps.version.outputs.version }}
+        run: |
+          if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "::error::Version is invalid. Expected format is X.Y.Z."
+            exit 1
+          fi
+
+      - name: Validate notes
+        if: inputs.create_release
+        env:
+          NOTES: ${{ steps.notes.outputs.notes }}
+        run: |
+          if [[ -z "$NOTES" ]]; then
+            echo "::error::Notes cannot be empty."
+            exit 1
+          fi
+
+  pypi-publish:
+    if: |
+      github.repository == 'nicotine-plus/nicotine-plus' &&
+      github.event_name == 'workflow_dispatch' && inputs.create_release
+    needs: [attestation, metadata]
+    runs-on: ubuntu-latest
+    timeout-minutes: 15
+    environment:
+      name: pypi
+      url: https://pypi.org/p/nicotine-plus
+    permissions:
+      id-token: write
+    steps:
+      - name: Download artifacts
+        uses: actions/download-artifact@v8
+        with:
+          name: python-dist
+          path: dist/
+
+      - name: Publish package to PyPI
+        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
+
+  github-release:
+    if: github.event_name == 'workflow_dispatch' && inputs.create_release
+    needs: [attestation, metadata]
+    runs-on: ubuntu-slim
+    timeout-minutes: 15
+    environment:
+      name: github-release
+    permissions:
+      contents: write
+      discussions: write
+    env:
+      GITHUB_TOKEN: ${{ github.token }}
+      VERSION: ${{ needs.metadata.outputs.version }}
+      NOTES: ${{ needs.metadata.outputs.notes }}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v6
+        with:
+          persist-credentials: false
+
+      - name: Download artifacts
+        uses: actions/download-artifact@v8
+        with:
+          path: dist/
+          skip-decompress: true
+          merge-multiple: true
+
+      - name: Prepare release assets
+        run: |
+          cd dist
+          unzip checksums.zip
+          rm checksums.zip python-dist.*
+          sha256sum --check ./*.sha256
+
+      - name: Create release
+        run: |
+          gh release create "$VERSION" \
+            --title "$VERSION" \
+            --notes "$NOTES" \
+            --discussion-category "Releases" \
+            dist/*
